# Generated by Django 3.0.8 on 2020-08-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_itemcategory_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Artist',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
