# Generated by Django 3.0.8 on 2020-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='BidWon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
