# Generated by Django 3.0.8 on 2020-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200804_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='listing'),
        ),
    ]
